DROP DATABASE IF EXISTS hackaton_character;
​
CREATE DATABASE hackaton_character;
​
USE hackaton_character;
​
CREATE TABLE characters (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(255) NOT NULL,
    image TEXT NULL,
    description TEXT NULL,
    loveStyle INT NOT NULL,
    food INT NOT NULL,
    ethic INT NOT NULL,
    partyMonster INT NOT NULL,
    fictional BOOL NULL,
    PRIMARY KEY (id)
);
​
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Janet Weiss', '22', 'Female', 'https://vignette.wikia.nocookie.net/rockyhorror/images/6/66/Janetport.png/revision/latest?cb=20160802162926', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 10, 20, 100, 60, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Brad Majors', '24', 'Male', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyOX4mc0eaGh4Y7AHEPM9BD7hAvwTrKEwx7UTyP5DxOwdgCgi8&s', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 10, 30, 60, 10, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Riff Raff', '103', 'Male', 'https://hobbydb-production.s3.amazonaws.com/processed_uploads/subject_photo/subject_photo/image/40343/1528225549-11555-4034/download_large.jpg', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 60, 40, 80, 90, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Magenta', '82', 'Female', 'https://www.scifinow.co.uk/wp-content/uploads/2019/07/tumblr_n9hvih2rok1sx2zfgo4_r1_1280-616x617.jpg', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.',50, 40, 60 , 90, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Rocky Horror', '1', 'Male', 'https://vignette.wikia.nocookie.net/rockyhorror/images/4/4f/Rockyport.png/revision/latest?cb=20160802163020', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 20, 20, 20, 20, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Everett V. Scott', '70', 'Male', 'https://i.pinimg.com/originals/9b/71/ac/9b71acdda35ed6cb9c6c83a967a7a32e.jpg', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 10, 10, 10, 10, true);
INSERT INTO `hackaton_character`.`characters` (`name`, `age`, `gender`, `image`, `description`, `loveStyle`, `food`, `ethic`, `partyMonster`, `fictional`) VALUES ('Frank-N-Furter', '86', 'Male', 'https://vignette.wikia.nocookie.net/rockyhorror/images/d/d9/Frankport.png/revision/latest?cb=20160802163635', 'Nam sole orto magnitudine angusti gurgitis sed profundi a transitu arcebantur et dum piscatorios quaerunt lenunculos vel innare temere contextis cratibus parant, effusae legiones, quae hiemabant tunc apud Siden, isdem impetu occurrere veloci. et signis prope ripam locatis ad manus comminus conserendas denseta scutorum conpage semet scientissime praestruebant, ausos quoque aliquos fiducia nandi vel cavatis arborum truncis amnem permeare latenter facillime trucidarunt.', 100, 100, 100, 100, true);