<?php


namespace App\Model;


class MatchManager extends AbstractManager
{

    /**
     * Created by PhpStorm.
     * User: sylvain
     * Date: 07/03/18
     * Time: 18:20
     * PHP version 7
     */

    const TABLE = 'characters';

    /**
     *  Initializes this class.
     */
    public function __construct()
    {
        parent::__construct(self::TABLE);
    }

    public function selectAll(): array
    {
        return parent::selectAll(); // TODO: Change the autogenerated stub
    }

    public function compareMatch() {

    }
}